# Generated by Django 4.1.3 on 2023-04-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_backgroundimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='backgroundimg_url',
            field=models.URLField(blank=True, null=True),
        ),

   
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='backgroundimg',
            field=models.ImageField(blank=True, default='images/resources/timeline-1.jpg', upload_to='background_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(blank=True, default='blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
