# Generated by Django 4.1.3 on 2023-04-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_image_url_profile_backgroundimg_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileimg_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]